site_name: Documentations
site_url: https://slynj.github.io/Documentations/
theme:
  name: material

  palette: 
    
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  font:
    text: Inter

  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tabs
    - navigation.top
    - navigation.sections
    - navigation.expand
    - navigation.path
    - toc.follow
    - content.code.copy
    - content.code.select

nav:
  - Home: index.md
  - 5G-Network:
    - 5G Core - Building Open5GS: "5G-Network/5G Core - Building Open5GS 17e011ff45b98048a6aff1a15e6d60a5.md"

markdown_extensions:
  - toc:
      permalink: true
  -  codehilite:
      guess_lang: false
      use_pygments: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra_css:
  - stylesheets/custom.css

extra:
  generator: false

plugins:
  - search:
      lang: en
      separator: "[\\s\\-]+"

